version: "3"

services:
  nitter:
    build:
      context: .
      dockerfile: self-contained.Dockerfile
    ports:
      - "8081:8081"
    volumes:
      # should map this in PaaS
      - nitter-data:/nitter-data
      # optional mapping for twitter-credentials.json file
      # - ./twitter-credentials.json:/nitter-data/twitter-credentials.json
    environment:
      # shuold be included for custom paths
      - NITTER_ACCOUNTS_FILE=/nitter-data/guest_accounts.json
      # optional twitter-credentials.json custom path
      # - TWITTER_CREDENTIALS_FILE=/nitter-data/twitter-credentials.json
      # optional instance custmizations from env
      - INSTANCE_TITLE=Custom title
      - INSTANCE_THEME=Twitter Dark
      - INSTANCE_INFINITE_SCROLL=1
      - INSTANCE_BASE64_MEDIA=1
      - INSTANCE_HOSTNAME=localhost:8081
      # - INSTANCE_HTTPS=1
      # optional for setups without redis and/or ng1inx
      # - DISABLE_REDIS=1
      # - DISABLE_NGINX=1
      # optional for setups without redis, e.g. external redis connection info
      # - REDIS_HOST=nitter-redis
      # - REDIS_PORT=6379
      # - REDIS_PASSWORD=
      # optional debugging flags
      - DEBUG=1
      - RESET_NITTER_ACCOUNTS_FILE=1
    env_file:
      # should require from env
      # TWITTER_USERNAME
      # TWITTER_PASSWORD
      # INSTANCE_RSS_PASSWORD
      # INSTANCE_WEB_USERNAME
      # INSTANCE_WEB_PASSWORD
      - .env
volumes:
  nitter-data:
