app = 'nitter'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
  dockerfile = 'self-contained.Dockerfile'

[[mounts]]
  source = 'nitter'
  destination = '/nitter-data'
  initial_size = '1gb'

[env]
  NITTER_ACCOUNTS_FILE = "/nitter-data/guest_accounts.json"

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1

[[http_service.checks]]
    interval = '10s'
    timeout = '5s'
    grace_period = '30s'
    method = 'GET'
    path = '/logo.png'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
